start-at-login = true
key-mapping.preset = 'qwerty'

after-login-command = []
after-startup-command = []

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

default-root-container-layout = 'tiles'
default-root-container-orientation = 'horizontal'

on-focused-monitor-changed = 'move-mouse monitor-lazy-center'
on-focus-changed = 'move-mouse window-lazy-center'

accordion-padding = 60

[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        10
outer.right =      10

[mode.main.binding]

alt-enter = 'exec-and-forget alacritty msg create-window || alacritty || open -a Terminal'

alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'
alt-o = 'fullscreen'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'focus-monitor left'
alt-shift-j = 'focus-monitor down'
alt-shift-k = 'focus-monitor up'
alt-shift-l = 'focus-monitor right'

alt-ctrl-h = 'move-workspace-to-monitor prev'
alt-ctrl-l = 'move-workspace-to-monitor next'

alt-g = 'mode grab'

alt-1 = 'workspace 1 --auto-back-and-forth'
alt-2 = 'workspace 2 --auto-back-and-forth'
alt-3 = 'workspace 3 --auto-back-and-forth'
alt-4 = 'workspace 4 --auto-back-and-forth'
alt-5 = 'workspace 5 --auto-back-and-forth'
alt-6 = 'workspace 6 --auto-back-and-forth'
alt-7 = 'workspace 7 --auto-back-and-forth'
alt-8 = 'workspace 8 --auto-back-and-forth'
alt-9 = 'workspace 9 --auto-back-and-forth'
alt-q = 'workspace Q --auto-back-and-forth'
alt-w = 'workspace W --auto-back-and-forth'
alt-e = 'workspace E --auto-back-and-forth'
alt-r = 'workspace R --auto-back-and-forth'
alt-t = 'workspace T --auto-back-and-forth'
alt-y = 'workspace Y --auto-back-and-forth'
alt-a = 'workspace A --auto-back-and-forth'
alt-s = 'workspace S --auto-back-and-forth'
alt-d = 'workspace D --auto-back-and-forth'
alt-f = 'workspace F --auto-back-and-forth'
alt-z = 'workspace Z --auto-back-and-forth'
alt-x = 'workspace X --auto-back-and-forth'
alt-c = 'workspace C --auto-back-and-forth'
alt-v = 'workspace V --auto-back-and-forth'
alt-b = 'workspace B --auto-back-and-forth'

alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
alt-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
alt-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
alt-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
alt-shift-9 = ['move-node-to-workspace 9', 'workspace 9']
alt-shift-q = ['move-node-to-workspace Q', 'workspace Q']
alt-shift-w = ['move-node-to-workspace W', 'workspace W']
alt-shift-e = ['move-node-to-workspace E', 'workspace E']
alt-shift-r = ['move-node-to-workspace R', 'workspace R']
alt-shift-t = ['move-node-to-workspace T', 'workspace T']
alt-shift-y = ['move-node-to-workspace Y', 'workspace Y']
alt-shift-a = ['move-node-to-workspace A', 'workspace A']
alt-shift-s = ['move-node-to-workspace S', 'workspace S']
alt-shift-d = ['move-node-to-workspace D', 'workspace D']
alt-shift-f = ['move-node-to-workspace F', 'workspace F']
alt-shift-g = ['move-node-to-workspace G', 'workspace G']
alt-shift-z = ['move-node-to-workspace Z', 'workspace Z']
alt-shift-x = ['move-node-to-workspace X', 'workspace X']
alt-shift-c = ['move-node-to-workspace C', 'workspace C']
alt-shift-v = ['move-node-to-workspace V', 'workspace V']
alt-shift-b = ['move-node-to-workspace B', 'workspace B']

[mode.grab.binding]

esc = ['reload-config', 'mode main']

h = 'move left'
j = 'move down'
k = 'move up'
l = 'move right'

shift-h = 'join-with left'
shift-j = 'join-with down'
shift-k = 'join-with up'
shift-l = 'join-with right'

f = ['layout floating tiling', 'mode main']

t = 'layout tiles horizontal vertical'
a = 'layout accordion horizontal vertical'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.Preview'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'ru.yandex.desktop.disk2'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'us.zoom.xos'
run = ['layout floating', 'move-node-to-workspace Z']

[[on-window-detected]]
if.app-id = 'ru.keepcoder.Telegram'
run = ['move-node-to-workspace T']
