start-at-login = true
key-mapping.preset = 'qwerty'

after-login-command = []
after-startup-command = []

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

default-root-container-layout = 'tiles'
default-root-container-orientation = 'horizontal'

on-focused-monitor-changed = 'move-mouse monitor-lazy-center'
on-focus-changed = 'move-mouse window-lazy-center'

accordion-padding = 15

[workspace-to-monitor-force-assignment]
1 = 'main'
2 = 'secondary'

[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        10
outer.right =      10

[mode.main.binding]

alt-enter = 'exec-and-forget alacritty msg create-window || alacritty || open -a Terminal'

alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'
alt-shift-f = 'fullscreen'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'focus-monitor left'
alt-shift-j = 'focus-monitor down'
alt-shift-k = 'focus-monitor up'
alt-shift-l = 'focus-monitor right'

alt-o = 'workspace-back-and-forth'
alt-g = 'mode grab'
alt-shift-g = 'mode w-grab'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-q = 'workspace Q'
alt-w = 'workspace W'
alt-e = 'workspace E'
alt-r = 'workspace R'
alt-t = 'workspace T'
alt-y = 'workspace Y'
alt-a = 'workspace A'
alt-s = 'workspace S'
alt-d = 'workspace D'
alt-f = 'workspace F'
alt-z = 'workspace Z'
alt-x = 'workspace X'
alt-c = 'workspace C'
alt-v = 'workspace V'
alt-b = 'workspace B'

[mode.grab.binding]

esc = ['reload-config', 'mode main']

minus = 'resize smart -50'
equal = 'resize smart +50'

h = 'move left'
j = 'move down'
k = 'move up'
l = 'move right'

shift-h = 'join-with left'
shift-j = 'join-with down'
shift-k = 'join-with up'
shift-l = 'join-with right'

f = ['layout floating tiling', 'mode main']

slash = 'layout tiles horizontal vertical'
comma = 'layout accordion horizontal vertical'

alt-1 = ['move-node-to-workspace 1', 'workspace 1']
alt-2 = ['move-node-to-workspace 2', 'workspace 2']
alt-3 = ['move-node-to-workspace 3', 'workspace 3']
alt-4 = ['move-node-to-workspace 4', 'workspace 4']
alt-5 = ['move-node-to-workspace 5', 'workspace 5']
alt-6 = ['move-node-to-workspace 6', 'workspace 6']
alt-7 = ['move-node-to-workspace 7', 'workspace 7']
alt-8 = ['move-node-to-workspace 8', 'workspace 8']
alt-9 = ['move-node-to-workspace 9', 'workspace 9']
alt-q = ['move-node-to-workspace Q', 'workspace Q']
alt-w = ['move-node-to-workspace W', 'workspace W']
alt-e = ['move-node-to-workspace E', 'workspace E']
alt-r = ['move-node-to-workspace R', 'workspace R']
alt-t = ['move-node-to-workspace T', 'workspace T']
alt-y = ['move-node-to-workspace Y', 'workspace Y']
alt-a = ['move-node-to-workspace A', 'workspace A']
alt-s = ['move-node-to-workspace S', 'workspace S']
alt-d = ['move-node-to-workspace D', 'workspace D']
alt-f = ['move-node-to-workspace F', 'workspace F']
alt-g = ['move-node-to-workspace G', 'workspace G']
alt-z = ['move-node-to-workspace Z', 'workspace Z']
alt-x = ['move-node-to-workspace X', 'workspace X']
alt-c = ['move-node-to-workspace C', 'workspace C']
alt-v = ['move-node-to-workspace V', 'workspace V']
alt-b = ['move-node-to-workspace B', 'workspace B']

alt-shift-h = ['move-node-to-monitor left', 'focus-monitor left']
alt-shift-j = ['move-node-to-monitor down', 'focus-monitor down']
alt-shift-k = ['move-node-to-monitor up', 'focus-monitor up']
alt-shift-l = ['move-node-to-monitor right', 'focus-monitor right']

[mode.w-grab.binding]

esc = 'mode main'

r = ['flatten-workspace-tree', 'mode main']

h = 'move-workspace-to-monitor prev'
l = 'move-workspace-to-monitor next'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.Preview'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'ru.yandex.desktop.disk2'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'us.zoom.xos'
run = ['layout floating', 'move-node-to-workspace Z']
