start-at-login = true
key-mapping.preset = 'qwerty'

after-login-command = []
after-startup-command = []

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

default-root-container-layout = 'tiles'
default-root-container-orientation = 'horizontal'

on-focused-monitor-changed = 'move-mouse monitor-lazy-center'
on-focus-changed = 'move-mouse window-lazy-center'

accordion-padding = 60

[gaps]
inner.horizontal = 16
inner.vertical =   16
outer.left =       16
outer.bottom =     16
outer.top =        16
outer.right =      16

[mode.main.binding]

alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'
alt-f = 'fullscreen'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'focus-monitor left'
alt-shift-j = 'focus-monitor down'
alt-shift-k = 'focus-monitor up'
alt-shift-l = 'focus-monitor right'

alt-ctrl-h = 'move-workspace-to-monitor prev'
alt-ctrl-l = 'move-workspace-to-monitor next'

alt-backspace = 'workspace-back-and-forth'

alt-w = 'mode win'
alt-o = 'mode open'

alt-z = 'workspace Z --auto-back-and-forth'
alt-x = 'workspace X --auto-back-and-forth'
alt-c = 'workspace C --auto-back-and-forth'
alt-v = 'workspace V --auto-back-and-forth'
alt-b = 'workspace B --auto-back-and-forth'
alt-n = 'workspace N --auto-back-and-forth'
alt-m = 'workspace M --auto-back-and-forth'

alt-shift-z = ['move-node-to-workspace Z', 'workspace Z']
alt-shift-x = ['move-node-to-workspace X', 'workspace X']
alt-shift-c = ['move-node-to-workspace C', 'workspace C']
alt-shift-v = ['move-node-to-workspace V', 'workspace V']
alt-shift-b = ['move-node-to-workspace B', 'workspace B']
alt-shift-n = ['move-node-to-workspace N', 'workspace N']
alt-shift-m = ['move-node-to-workspace M', 'workspace M']

[mode.win.binding]

esc = ['reload-config', 'mode main']
enter = ['reload-config', 'mode main']

h = 'move left'
j = 'move down'
k = 'move up'
l = 'move right'

shift-h = 'join-with left'
shift-j = 'join-with down'
shift-k = 'join-with up'
shift-l = 'join-with right'

f = ['layout floating tiling', 'mode main']

t = 'layout tiles horizontal vertical'
a = 'layout accordion horizontal vertical'

[mode.open.binding]

esc = 'mode main'

t = ['exec-and-forget alacritty msg create-window || alacritty || open -a Terminal', 'mode main']
m = ['exec-and-forget open -a Telegram', 'mode main']
b = ['exec-and-forget open -a Arc', 'mode main']
c = ['exec-and-forget open -a Neovide', 'mode main']
s = ['exec-and-forget open -a Settings', 'mode main']

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.Preview'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'ru.yandex.desktop.disk2'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.neovide.neovide'
run = ['layout tiling', 'move-node-to-workspace C']

[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = ['layout tiling', 'move-node-to-workspace B']

[[on-window-detected]]
if.app-id = 'us.zoom.xos'
run = ['layout floating', 'move-node-to-workspace Z']

[[on-window-detected]]
if.app-id = 'ru.keepcoder.Telegram'
run = ['layout tiling', 'move-node-to-workspace M']
