[window]
blur = true
decorations = "Buttonless"
dynamic_padding = true
opacity = 0.75
padding = { x = 10, y = 10 }

[font]
normal = { family = "Iosevka Nerd Font Mono", style = "Regular" }
bold = { family = "Iosevka Nerd Font Mono", style = "Bold" }
italic = { family = "Iosevka Nerd Font Mono", style = "Italic" }
bold_italic = { family = "Iosevka Nerd Font Mono", style = "Bold Italic" }

size = 16
