#!/bin/bash

command-exists() {
  command -v "$1" &> /dev/null
}

if command-exists brew; then
    brew bundle --file=./packages/Brewfile
fi

if command-exists scoop; then
    scoop import ./packages/scoop.json
fi

if ! command-exists python3 && command-exists mise; then
    mise use --global python
fi

./link ./packages/.link.json

if command-exists mise; then
    mise install
fi

./link ./*/.link.json
