format = """
[](intro)\
[](bg:intro fg:env)\
$os\
$username\
[](fg:env bg:dir)\
$directory\
[](fg:dir bg:duration)\
$cmd_duration\
[](fg:duration bg:status)\
$status\
[](fg:status bg:outro)\
[ ](fg:outro)\
"""

palette = 'custom'

[palettes.custom]
intro = '#b34b37'
env = '#e66147'
env-text = 'bright-white'
dir = '#e64553'
dir-text = 'bright-white'
duration = '#b1355e'
duration-text = 'bright-white'
status = '#7e2559'
status-text = 'bright-white'
outro = '#4b1634'

[os]
format = '[$symbol](bg:env fg:env-text bold)'
disabled = false

[os.symbols]
Windows = ''
Ubuntu = ''
Raspbian = ''
Macos = ''

[username]
format = '[ $user](bg:env fg:env-text)'

[directory]
style = 'bg:dir fg:dir-text'
format = '[ $path]($style)'
use_os_path_sep = false
truncation_length = 3
truncation_symbol = '﬌/'

[directory.substitutions]
"Projects" = ''
"Documents" = ''
"Downloads" = ''
"Music" = ''
"Python" = ''
"Java" = ''
"JS" = ''
"CSharp" = ''
"Cpp" = ''
"Unity" = ''
"University" = ''
"node_modules" = ''
".github" = ''
".git" = ''
"/mnt" = ''

[cmd_duration]
style = 'bg:duration fg:duration-text'
format = '[ $duration]($style)'

[status]
style = 'bg:status fg:status-text'
format = '[ $int]($style)'
disabled = false
