format = """
[](before-dir)\
[](bg:before-dir fg:dir)\
$directory\
[](fg:dir bg:tech-env)\
$dotnet\
$python\
$java\
$nodejs\
[](fg:tech-env bg:git)\
$git_branch\
$git_commit\
$git_status\
$git_state\
[](fg:git bg:duration)\
$cmd_duration\
[](fg:duration bg:status)\
$status\
[](fg:status bg:after-status)\
[ ](fg:after-status)\
"""

palette = 'catppuccin'

[palettes.custom]
before-dir = '#a30048'
dir = '#d7005f'
dir-text = 'bright-white'
tech-env = '#4f1dc2'
tech-env-text = 'bright-white'
git = '#e74b27'
git-text = 'bright-white'
duration = '#ffce3e'
duration-text = 'black'
status = '#eb2a41'
status-text = 'bright-white'
after-status = '#9c0b1c'

[palettes.catppuccin]
before-dir = '#992e37'
dir = '#e64553'
dir-text = 'bright-white'
tech-env = '#7287fd'
tech-env-text = 'bright-white'
git = '#fe640b'
git-text = 'bright-white'
duration = '#ebddaa'
duration-text = '#5c5f77'
status = '#a6da95'
status-text = '#4c4f69'
after-status = '#6b8d60'

[directory]
style = 'bg:dir fg:dir-text'
format = '[ﱮ $path]($style)'
use_os_path_sep = false
truncation_length = 3
truncation_symbol = '﬌/'

[directory.substitutions]
"Projects" = ''
"Documents" = ''
"Downloads" = ''
"Music" = ''
"Python" = ''
"Java" = ''
"JS" = ''
"CSharp" = ''
"Cpp" = ''
"Unity" = ''
"node_modules" = ''
".github" = ''
".git" = ''

[git_branch]
symbol = ''
style = 'bg:git fg:git-text'
format = '[ $symbol $branch(:$remote_branch)]($style)'

[git_commit]
tag_symbol = ""
style = 'bg:git fg:git-text bold'
format = '[  $hash$tag]($style)'

[git_status]
style = 'bg:git fg:git-text bold'
format = '[( \[$all_status$ahead_behind\])]($style)'
ahead = '{count}'
behind = '{count}'
diverged = '${ahead_count}${behind_count}'

[git_state]
style = 'bg:git fg:git-text bold'
format = '[ $state( $progress_current/$progress_total)]($style)'

[java]
symbol = ''
style = 'bg:tech-env fg:tech-env-text'
format = '[ $symbol ($version)]($style)'

[nodejs]
symbol = ''
style = 'bg:tech-env fg:tech-env-text'
format = '[ $symbol ($version)]($style)'

[dotnet]
symbol = ''
style = 'bg:tech-env fg:tech-env-text'
version_format = 'v${major}.${minor}'
format = '[ $symbol ($version)]($style)'
detect_extensions = ["csproj", "sln"]

[python]
symbol = ''
style = 'bg:tech-env fg:tech-env-text'
format = '[ $symbol ($version)( \($virtualenv\))]($style)'

[status]
style = 'bg:status fg:status-text'
symbol = ''
format = '[ $symbol ($maybe_int)]($style)'
disabled = false

[cmd_duration]
style = 'bg:duration fg:duration-text'
format = '[  $duration]($style)'
