format = "$os$username$directory$cmd_duration$status > "

add_newline = false

palette = 'custom'

[palettes.custom]
os = '#bright-white'
username = '#47c158'
dir = '#bright-white'
duration = '#cbcb41'
status = '#b487f4'

[os]
format = '[ $symbol](fg:os bold)'
disabled = false

[os.symbols]
Windows = ''
Ubuntu = ''
Raspbian = ''
Macos = ''

[username]
format = '[ $user](fg:username)'

[directory]
style = 'fg:dir'
format = '[ $path]($style)'
use_os_path_sep = false
truncation_length = 3
truncation_symbol = '󱞩/'

[cmd_duration]
style = 'fg:duration'
format = '[ $duration]($style)'

[status]
style = 'fg:status'
format = '[ $int]($style)'
disabled = false

[directory.substitutions]
"Projects" = ''
"Documents" = ''
"Downloads" = ''
"Music" = ''
"Python" = ''
"Java" = ''
"JS" = ''
"CSharp" = ''
"Cpp" = ''
"Unity" = ''
"University" = ''
"node_modules" = ''
".github" = ''
".git" = ''
"/mnt" = ''
