format = "[](dimmed yellow) $directory$cmd_duration$python$status [❯](blue) "

add_newline = false

palette = 'custom'

[palettes.custom]
username = '#47c158'
dir = 'bright-blue'
duration = '#cbcb41'
status = '#b487f4'
python = 'bright-green'

[directory]
format = '[$path]($style)'
style = 'fg:dir'
use_os_path_sep = false
truncation_length = 3
truncate_to_repo = false
truncation_symbol = '/'

[cmd_duration]
format = '[ $duration]($style)'
style = 'fg:duration'

[status]
format = '[ $int]($style)'
style = 'fg:status'
disabled = false

[python]
format = '[ 󰌠( $virtualenv)]($style)'
style = 'fg:python'
detect_folders = ['venv']

[directory.substitutions]
"Repos" = ''
"Documents" = ''
"Downloads" = ''
