require 'keymaps.nvim.buffer'
require 'keymaps.nvim.colorscheme'
require 'keymaps.nvim.motion'
require 'keymaps.nvim.quickfix'
require 'keymaps.nvim.quit'
require 'keymaps.nvim.selection'
require 'keymaps.nvim.tab'
require 'keymaps.nvim.window'
