[settings]
trusted_config_paths = ["~/.config"]

idiomatic_version_file_enable_tools = ["node", "python"]

[tools]
deno = "latest"
node = "latest"
python = { version = "3.14", _.python.venv = { path = ".venv", create = true } }
uv = "latest"

difftastic = "latest"
fzf = "latest"
jq = "latest"
just = "latest"
lazygit = "latest"
neovim = "latest"
opencode = "latest"
ripgrep = "latest"
starship = "latest"
tree-sitter = "latest"
yazi = "latest"
zellij = { version = "latest", os = ["macos", "linux"] }
zoxide = "latest"
