[settings]
trusted_config_paths = ["~/.config"]
minimum_release_age = "7d"
prefer_offline = true

idiomatic_version_file_enable_tools = ["node", "python"]

[tools]
deno = "latest"
node = "latest"
python = { version = "3.14", _.python.venv = { path = ".venv", create = true } }
uv = "latest"

difftastic = "latest"
fd = "latest"
fzf = "latest"
jq = "latest"
just = "latest"
lazygit = "latest"
neovim = "latest"
opencode = "latest"
ripgrep = "latest"
starship = "latest"
tree-sitter = "latest"
watchexec = "latest"
yazi = "latest"
zellij = "latest"
zoxide = "latest"
